name: Stock Bot Daily

on:
  schedule:
    - cron: '30 23 * * *'  # 毎日08:30 JST（日本時間）に実行（UTCで23:30）
  workflow_dispatch:  # 手動実行もOK

jobs:
  run-stock-bot:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 必要なライブラリをインストール
        run: |
          pip install yfinance ta requests pandas

      - name: 株価予測Botを実行
        run: python main.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
