name: Stock Bot

on:
  schedule:
    - cron: '30 23 * * *'  # 毎日08:30 JST（23:30 UTC）
  workflow_dispatch:      # 手動実行も許可

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install yfinance ta requests pandas

    - name: Run script
      run: python main.py
