- name: Install dependencies
  run: pip install yfinance pandas ta requests
- name: Download CSV (update_db.py)
  run: python update_db.py
- name: Score & Slack notify (main.py)
  run: python main.py
